-- 005_page_sections.sql
--
-- The last of the page copy that still lived in TypeScript: the "What I take on"
-- cards and questions on /contact, and the stack-evidence table and questions on
-- /skills. Merged into the existing `pages` row rather than given rows of their own,
-- so all per-page copy stays in one place.
--
-- Idempotent: re-running overwrites these keys with the same seed content.

update site_config
set value = jsonb_set(
      jsonb_set(
        value,
        '{contact}',
        coalesce(value->'contact', '{}'::jsonb) || ($mg${"cards":[{"title":"Build an MVP","body":"A first working version for a product that does not exist yet, scoped to the smallest thing that can be put in front of real users. Most of the case studies on this site started here."},{"title":"Ship a feature into an existing product","body":"Joining a codebase someone else started — adding a payments flow, a mobile app alongside a web product, an admin surface the team has been deferring."},{"title":"Fix what is slow or breaking","body":"Performance and reliability work. Previous examples include cutting initial load time by 30% with server-side rendering and making an admin panel load five times faster."}],"qa":[{"q":"How do I hire Meghraj Giri?","a":"Send a message through the form on this page or email meghrajgiri56@gmail.com with what you are building, roughly when you need it, and any constraints that matter. Replies usually come within 24 hours."},{"q":"Where is he based, and does that matter for remote work?","a":"Meghraj Giri works from Butwal, Nepal, on UTC+5:45. That overlaps a full working day with Australia and most of Asia, and the early morning in Europe. Clients in the United States typically get a same-day reply and a scheduled overlap window rather than live afternoon hours."},{"q":"Does he work with clients outside Nepal?","a":"Yes. Current and past work includes clients in Australia and the United States alongside Nepali companies, and he has been a Toptal Verified Expert in Engineering since March 2026."},{"q":"What does he need to give a useful answer?","a":"What the product does, who it is for, whether it is web, mobile or both, and any hard deadline. A rough budget range helps, but the scope conversation is more useful than a number."}]}$mg$::jsonb)
      ),
      '{skills}',
      coalesce(value->'skills', '{}'::jsonb) || ($mg${"evidence":[{"tech":"React Native + Expo","where":"Thriftverse, a thrift marketplace shipped to iOS and Android with eSewa checkout and Nepal Can Move logistics","slug":"thriftverse"},{"tech":"Next.js + MedusaJS","where":"Cannabiz Elite, a clinic management system for Australian cannabis and telehealth practices","slug":"cannabiz-elite"},{"tech":"Firebase + GraphQL","where":"Lyve, a marketplace for event tickets and costume reservation resale","slug":"lyve"},{"tech":"Supabase + PWA","where":"Khatapata, an offline-capable inventory system installable from the browser","slug":"khatapata"},{"tech":"Next.js + Nest.js","where":"College Cost Secrets, a fin-tech advisory platform in the education market","slug":"college-cost-secrets"},{"tech":"WebSockets","where":"Bookvid, a live video booking marketplace","slug":"bookvid"},{"tech":"Stream Chat","where":"Yume, a gambling-recovery app with peer support built in","slug":"yume"}],"qa":[{"q":"What tech stack does Meghraj Giri use?","a":"Meghraj Giri builds primarily in the React ecosystem: React, Next.js and TypeScript on the web, React Native and Expo for mobile, and Node.js with PostgreSQL, Supabase or Firebase behind them. He has shipped production work on all of these across seven published case studies."},{"q":"Does he build mobile apps as well as websites?","a":"Yes. Meghraj Giri has shipped React Native applications to both the App Store and Google Play, including Thriftverse and Lyve, and spent two years as a React Native developer at Inseed Tech building cross-platform apps from a shared monorepo."},{"q":"What kind of products has he worked on?","a":"Mostly transactional, multi-sided products: marketplaces, clinic and telehealth systems, inventory tools and reservation platforms. The domains span e-commerce, healthcare, fin-tech and ed-tech."}]}$mg$::jsonb)
    )
where key = 'pages';
